/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brain.report;

import brain.controller.ClsHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author Brain
 */
public class PnlReportEntry extends javax.swing.JPanel {

    /**
     * Creates new form PnlReportEntry
     */
    public PnlReportEntry() {
        initComponents();
        try
        {
            ClsHelper.Load_CmbBox(cmbAnnee, "SELECT annee FROM tAnnee ORDER BY annee DESC");
            ClsHelper.Load_CmbBox(cmbMois, "SELECT mois FROM tMois");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :\n"+e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbMois = new javax.swing.JComboBox<>();
        cmbAnnee = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEntreeV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbEtat = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/Car.png"))); // NOI18N
        jLabel1.setText("RAPPORT DES ENTREES");

        cmbMois.setEditable(true);
        cmbMois.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowRightShadow(false);
        cmbMois.setBorder(dropShadowBorder1);
        cmbMois.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbMoisPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmbAnnee.setEditable(true);
        cmbAnnee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annee" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowRightShadow(false);
        cmbAnnee.setBorder(dropShadowBorder2);
        cmbAnnee.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbAnneePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tabEntreeV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tabEntreeV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tabEntreeV);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/print.png"))); // NOI18N
        jLabel2.setText("Imprimer");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        cmbEtat.setEditable(true);
        cmbEtat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEtat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etat de Paiement", "A facturer", "A Recouvrer", "A Recouvrer en Totalité", "Payé en totalité", " " }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowRightShadow(false);
        cmbEtat.setBorder(dropShadowBorder3);
        cmbEtat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbEtatPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbMois, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(864, 864, 864)))
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMois, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMoisPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbMoisPopupMenuWillBecomeInvisible
        try
        {
            ClsHelper.Load_TblData(tabEntreeV, "SELECT e.id ID, e.date_entree DATE_ENTREE, e.numero NUM, e.plaque PLAQUE, "
                        + "e.nature_mese [M/SE], e.declarant DECLARANT, e.agence AGENGE, "
                        + "e.importateur IMPORTATEUR, e.poids_reel POIDS_REEL, e.date_sortie DATE_SORTIE, "
                        + "e.etat_facturation ETAT FROM tEntry_Vehicule e "
                        + "INNER JOIN tMois m on e.idMois = m.id "
                        + "INNER JOIN tAnnee a on e.idAnnee = a.id "
                        + "WHERE e.etat_facturation = '"+cmbEtat.getSelectedItem().toString()+"' "
                        + "AND m.mois = '"+cmbMois.getSelectedItem().toString()+"' "
                + "AND a.annee = '"+cmbAnnee.getSelectedItem().toString()+"'");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :\n"+e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbMoisPopupMenuWillBecomeInvisible

    private void cmbAnneePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbAnneePopupMenuWillBecomeInvisible
        try
        {
            ClsHelper.Load_TblData(tabEntreeV, "SELECT e.id ID, e.date_entree DATE_ENTREE, e.numero NUM, e.plaque PLAQUE, "
                        + "e.nature_mese [M/SE], e.declarant DECLARANT, e.agence AGENGE, "
                        + "e.importateur IMPORTATEUR, e.poids_reel POIDS_REEL, e.date_sortie DATE_SORTIE, "
                        + "e.etat_facturation ETAT FROM tEntry_Vehicule e "
                        + "INNER JOIN tMois m on e.idMois = m.id "
                        + "INNER JOIN tAnnee a on e.idAnnee = a.id "
                        + "WHERE e.etat_facturation = '"+cmbEtat.getSelectedItem().toString()+"' "
                        + "AND m.mois = '"+cmbMois.getSelectedItem().toString()+"' "
                + "AND a.annee = '"+cmbAnnee.getSelectedItem().toString()+"'");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :\n"+e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbAnneePopupMenuWillBecomeInvisible

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //code to print
        try 
        {
            frmReport pr=new frmReport();
            ClsLoad_Report.Print_Report("src\\brain\\report\\rpt_entrryV.jrxml", 
                "SELECT e.id ID, e.date_entree DATE_ENTREE, e.numero NUM, e.plaque PLAQUE, "
                        + "e.nature_mese [M/SE], e.declarant DECLARANT, e.agence AGENGE, "
                        + "e.importateur IMPORTATEUR, e.poids_reel POIDS_REEL, e.date_sortie DATE_SORTIE, "
                        + "e.etat_facturation ETAT FROM tEntry_Vehicule e "
                        + "INNER JOIN tMois m on e.idMois = m.id "
                        + "INNER JOIN tAnnee a on e.idAnnee = a.id "
                        + "WHERE e.etat_facturation = '"+cmbEtat.getSelectedItem().toString()+"' "
                        + "AND m.mois = '"+cmbMois.getSelectedItem().toString()+"' "
                + "AND a.annee = '"+cmbAnnee.getSelectedItem().toString()+"'", pr);
            pr.setVisible(true);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }   
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cmbEtatPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbEtatPopupMenuWillBecomeInvisible
        try
        {
            ClsHelper.Load_TblData(tabEntreeV, "SELECT e.id ID, e.date_entree DATE_ENTREE, e.numero NUM, e.plaque PLAQUE, "
                        + "e.nature_mese [M/SE], e.declarant DECLARANT, e.agence AGENGE, "
                        + "e.importateur IMPORTATEUR, e.poids_reel POIDS_REEL, e.date_sortie DATE_SORTIE, "
                        + "e.etat_facturation ETAT FROM tEntry_Vehicule e "
                        + "INNER JOIN tMois m on e.idMois = m.id "
                        + "INNER JOIN tAnnee a on e.idAnnee = a.id "
                        + "WHERE e.etat_facturation = '"+cmbEtat.getSelectedItem().toString()+"' "
                        + "AND m.mois = '"+cmbMois.getSelectedItem().toString()+"' "
                + "AND a.annee = '"+cmbAnnee.getSelectedItem().toString()+"'");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error :\n"+e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbEtatPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAnnee;
    private javax.swing.JComboBox<String> cmbEtat;
    private javax.swing.JComboBox<String> cmbMois;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabEntreeV;
    // End of variables declaration//GEN-END:variables
}
