/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brain.gui.pnl;

import brain.controller.ClsHelper;
import brain.controller.DbConnect;
import brain.gui.frmPaiement;
import brain.model.ClsAnnee;
import brain.model.ClsEntry_Vehicule;
import brain.model.ClsFacturation;
import brain.model.ClsMois;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brain
 */
public class PnlFacturation extends javax.swing.JPanel {

    ClsAnnee an = new ClsAnnee();
    ClsMois mois = new ClsMois();
    ClsFacturation fact = new ClsFacturation();
    ClsEntry_Vehicule ev = new ClsEntry_Vehicule();

    /**
     * Creates new form PnlFacturation
     */
    public PnlFacturation() {
        initComponents();
        setTextVide();
        try {
            getEntry_Element(cmbIdVehicule.getSelectedItem().toString());
            ClsHelper.Load_CmbBox(cmbAnnee, "SELECT annee FROM tAnnee ORDER BY annee DESC");
            ClsHelper.Load_CmbBox(cmbMois, "SELECT mois FROM tMois");
            ClsHelper.Load_CmbBox(cmbIdVehicule, "SELECT CONCAT(id,' - ',date_entree,' - ', plaque, ' - ', numero) "
                    + "FROM tEntry_Vehicule");

            ClsHelper.Load_TblData(jTable1, "SELECT f.id ID, CONCAT(e.id,' - ',e.date_entree,' - ', e.plaque, ' - ', e.numero) VEHICULE, "
                    + "f.date_sortie DATE_SORTIE, f.nom_client_fidele CLIENT, f.[description] [DESCRIPTION], f.poids_facture POIDS_FACTURE, "
                    + "f.nbre_jour NOMBRE_JOURS, f.parking PARKING, f.sureveillance_1 [SURV 1], f.sureveillance_2 [SURV 2], f.manutention MANUTENTION, "
                    + "f.tva TVA, f.frais_admin FRAIS_ADMIN, f.total MONTANT_TOTAL FROM tFacturation f "
                    + "INNER JOIN tEntry_Vehicule e ON f.idEntree_vehicule = e.id "
                    + "INNER JOIN tMois m ON f.idMois = m.id "
                    + "INNER JOIN tAnnee a ON f.idAnnee = a.id "
                    + "WHERE m.mois = '" + cmbMois.getSelectedItem().toString() + "' "
                    + "AND a.annee = '" + cmbAnnee.getSelectedItem().toString() + "'");

            txtId.setText("FACT0" + ClsHelper.Increment_IDStr("tFacturation"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Facturation Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void setTextVide() {
        lbIdEntry.setText("");
        lb_dateEntree.setText("");
        lb_Num.setText("");
        lb_Plaque.setText("");
        lb_nature.setText("");
        lb_declarant.setText("");
        lb_poid.setText("");
    }

    private void getEntry_Element(String idValue) {
        //selectionne une entree de vehicule et donne les informations sur cete entree
        try {
            PreparedStatement ps = DbConnect.connectDb().prepareStatement("SELECT * FROM tEntry_Vehicule WHERE CONCAT(id,' - ',date_entree,' - ', plaque, ' - ', numero) = ?");
            ps.setString(1, idValue);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                lbIdEntry.setText("ID: " + rs.getString("id"));
                lb_dateEntree.setText("Date: " + rs.getString("date_entree"));
                lb_Num.setText("Numéro: " + rs.getString("numero"));
                lb_Plaque.setText("laque: " + rs.getString("plaque"));
                lb_nature.setText("M/se: " + rs.getString("nature_mese"));
                lb_declarant.setText("Déclarant: " + rs.getString("declarant"));
                lb_poid.setText("Poids: " + rs.getString("poids_reel"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "fetch_Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void changeStateEntry(String myId) {
        try {
            PreparedStatement ps = DbConnect.connectDb().prepareStatement("UPDATE tEntry_Vehicule "
                    + "SET etat_facturation = 'A Recouvrer en totalité' "
                    + "WHERE CONCAT(id,' - ',date_entree,' - ', plaque, ' - ', numero) = ?");
            ps.setString(1, myId);
            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "changeStateEntry Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbMois = new javax.swing.JComboBox<>();
        cmbAnnee = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPoids = new javax.swing.JTextField();
        txtSurv1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClient_Fidele = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtManutention = new javax.swing.JTextField();
        txtParking = new javax.swing.JTextField();
        cmbIdVehicule = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSurv2 = new javax.swing.JTextField();
        txtFraisAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTva = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNbreJour = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lbCalcul = new javax.swing.JLabel();
        lbIdEntry = new javax.swing.JLabel();
        lb_dateEntree = new javax.swing.JLabel();
        lb_Num = new javax.swing.JLabel();
        lb_declarant = new javax.swing.JLabel();
        lb_nature = new javax.swing.JLabel();
        lb_Plaque = new javax.swing.JLabel();
        lb_poid = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowRightShadow(false);
        jXDatePicker1.setBorder(dropShadowBorder1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("DATE SORTIE");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/add.png"))); // NOI18N
        jLabel13.setText("Nouveau");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jLabel13.setBorder(dropShadowBorder2);
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/delete.png"))); // NOI18N
        jLabel16.setText("Supprimer");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        jLabel16.setBorder(dropShadowBorder3);
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/accept.png"))); // NOI18N
        jLabel15.setText("Enregistrer");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        jLabel15.setBorder(dropShadowBorder4);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/money_b.png"))); // NOI18N
        jLabel1.setText("FACTURATION");

        cmbType.setEditable(true);
        cmbType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TYPE DE FACTURATION", "FACTURATION NORMALE", "IT", "CLIENT FIDELE", "AUTRE FACTURATION" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowRightShadow(false);
        cmbType.setBorder(dropShadowBorder5);
        cmbType.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbTypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Passer au paiement >>>");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        jLabel19.setBorder(dropShadowBorder6);
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        cmbMois.setEditable(true);
        cmbMois.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowRightShadow(false);
        cmbMois.setBorder(dropShadowBorder7);
        cmbMois.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbMoisPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmbAnnee.setEditable(true);
        cmbAnnee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annee" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setShowRightShadow(false);
        cmbAnnee.setBorder(dropShadowBorder8);
        cmbAnnee.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbAnneePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Total");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder9 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder9.setShowRightShadow(false);
        txtTotal.setBorder(dropShadowBorder9);

        txtPoids.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPoids.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder10 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder10.setShowRightShadow(false);
        txtPoids.setBorder(dropShadowBorder10);

        txtSurv1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSurv1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder11 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder11.setShowRightShadow(false);
        txtSurv1.setBorder(dropShadowBorder11);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Manutention");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Frais Admin.");

        txtClient_Fidele.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClient_Fidele.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder12 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder12.setShowRightShadow(false);
        txtClient_Fidele.setBorder(dropShadowBorder12);

        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescription.setText("BONUS");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder13 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder13.setShowRightShadow(false);
        txtDescription.setBorder(dropShadowBorder13);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setText("Vehicule");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("TVA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Parking");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Nbre Jours");

        txtManutention.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtManutention.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder14 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder14.setShowRightShadow(false);
        txtManutention.setBorder(dropShadowBorder14);

        txtParking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtParking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder15 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder15.setShowRightShadow(false);
        txtParking.setBorder(dropShadowBorder15);

        cmbIdVehicule.setEditable(true);
        cmbIdVehicule.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbIdVehicule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECTIONNER VEHICULE" }));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder16 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder16.setShowRightShadow(false);
        cmbIdVehicule.setBorder(dropShadowBorder16);
        cmbIdVehicule.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbIdVehiculePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Surveil. 2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Surveil. 1");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setText("ID");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Déscription");

        txtSurv2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSurv2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder17 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder17.setShowRightShadow(false);
        txtSurv2.setBorder(dropShadowBorder17);

        txtFraisAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFraisAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder18 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder18.setShowRightShadow(false);
        txtFraisAdmin.setBorder(dropShadowBorder18);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Poids Fact.");

        txtTva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder19 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder19.setShowRightShadow(false);
        txtTva.setBorder(dropShadowBorder19);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Client Fidèle");

        txtNbreJour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNbreJour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder20 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder20.setShowRightShadow(false);
        txtNbreJour.setBorder(dropShadowBorder20);
        txtNbreJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNbreJourActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder21 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder21.setShowRightShadow(false);
        txtId.setBorder(dropShadowBorder21);

        lbCalcul.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbCalcul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCalcul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brain/gui/img/calculate.png"))); // NOI18N
        lbCalcul.setText("Calculer");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder22 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder22.setShowLeftShadow(true);
        dropShadowBorder22.setShowTopShadow(true);
        lbCalcul.setBorder(dropShadowBorder22);
        lbCalcul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCalcul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCalculMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParking))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNbreJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPoids))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescription))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClient_Fidele))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbIdVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtManutention))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTva))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFraisAdmin))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotal))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSurv2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSurv1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbCalcul, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbIdVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClient_Fidele, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNbreJour, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtSurv1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSurv2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManutention, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTva, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFraisAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbCalcul, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtParking, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbIdEntry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbIdEntry.setText("jLabel2");

        lb_dateEntree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_dateEntree.setText("jLabel2");

        lb_Num.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_Num.setText("jLabel2");

        lb_declarant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_declarant.setText("jLabel2");

        lb_nature.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_nature.setText("jLabel2");

        lb_Plaque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_Plaque.setText("jLabel2");

        lb_poid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_poid.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbIdEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_dateEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_Plaque, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_nature, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_declarant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_poid, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMois, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbIdEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_dateEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Plaque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nature, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_declarant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_poid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        frmPaiement paie = new frmPaiement();
        paie.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void cmbTypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbTypePopupMenuWillBecomeInvisible
        try {
            if (cmbType.getSelectedItem().toString().equals("IT")) {
                txtParking.setText("");
                txtNbreJour.setText("");
                txtDescription.setText("FACTURATION IT");
                txtClient_Fidele.setText("NON");
                txtFraisAdmin.setEnabled(false);
                txtFraisAdmin.setText("");
                txtManutention.setEnabled(false);
                txtManutention.setText("");
                txtPoids.setEnabled(false);
                txtPoids.setText("");
                txtSurv1.setEnabled(false);
                txtSurv1.setText("");
                txtSurv2.setEnabled(false);
                txtSurv2.setText("");
                txtTva.setEnabled(false);
                txtTva.setText("");
                txtParking.setEnabled(true);
                txtNbreJour.setEnabled(true);
            } else if (cmbType.getSelectedItem().toString().equals("CLIENT FIDELE")) {
                txtParking.setText("");
                txtNbreJour.setText("");
                txtDescription.setText("CLIENT FIDELE");
                txtClient_Fidele.setEnabled(true);
                txtClient_Fidele.setText("");
                txtParking.setEnabled(false);
                txtPoids.setEnabled(false);
                txtFraisAdmin.setEnabled(false);
                txtManutention.setEnabled(false);
                txtPoids.setEnabled(false);
                txtSurv1.setEnabled(false);
                txtSurv2.setEnabled(false);
                txtTva.setEnabled(false);
                txtNbreJour.setEnabled(false);
                txtTva.setText("");
                txtSurv2.setText("");
                txtSurv1.setText("");
                txtPoids.setText("");
                txtManutention.setText("");
                txtFraisAdmin.setText("");
                txtPoids.setText("");
            } else if (cmbType.getSelectedItem().toString().equals("AUTRE FACTURATION")) {
                txtDescription.setText("AUTRE FACTURATION");
                txtClient_Fidele.setEnabled(true);
                txtClient_Fidele.setText("NON");
                txtParking.setEnabled(false);
                txtPoids.setEnabled(false);
                txtFraisAdmin.setEnabled(false);
                txtManutention.setEnabled(false);
                txtPoids.setEnabled(false);
                txtSurv1.setEnabled(false);
                txtSurv2.setEnabled(false);
                txtTva.setEnabled(false);
                txtNbreJour.setEnabled(false);
                txtParking.setText("");
                txtPoids.setText("");
                txtFraisAdmin.setText("");
                txtPoids.setText("");
                txtSurv1.setText("");
                txtSurv2.setText("");
                txtTva.setText("");
                txtNbreJour.setText("");
                txtManutention.setText("");
            } else if (cmbType.getSelectedItem().toString().equals("FACTURATION NORMALE")) {
                txtParking.setText("");
                txtNbreJour.setText("");
                txtDescription.setText("AUTRE FACTURATION");
                txtClient_Fidele.setEnabled(true);
                txtClient_Fidele.setText("NON");
                txtParking.setEnabled(true);
                txtPoids.setEnabled(true);
                txtFraisAdmin.setEnabled(true);
                txtManutention.setEnabled(true);
                txtPoids.setEnabled(true);
                txtSurv1.setEnabled(true);
                txtSurv2.setEnabled(true);
                txtTva.setEnabled(true);
                txtNbreJour.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbTypePopupMenuWillBecomeInvisible

    private void txtNbreJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNbreJourActionPerformed

    }//GEN-LAST:event_txtNbreJourActionPerformed

    private void lbCalculMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCalculMouseClicked
        if (cmbType.getSelectedItem().toString().equals("IT")) {
            if (!txtParking.getText().isEmpty() || !txtNbreJour.getText().isEmpty()) {
                float park = Float.valueOf(txtParking.getText());
                float nbre = Float.valueOf(txtNbreJour.getText());
                float tot = park * nbre;
                txtTotal.setText("" + tot);
            }
        } else if (cmbType.getSelectedItem().toString().equals("CLIENT FIDELE")) {
        } else if (cmbType.getSelectedItem().toString().equals("AUTRE FACTURATION")) {
        } else if (cmbType.getSelectedItem().toString().equals("FACTURATION NORMALE")) {
            if (txtManutention.getText().isEmpty() || txtFraisAdmin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Entrez le montant de manutention ou des frais administratifs",
                        "Facturation Error", JOptionPane.WARNING_MESSAGE);
            } else {
                float poids, park, nbre, surv1, surv2, manut, fradmin;
                poids = Float.valueOf(txtPoids.getText());
                park = Float.valueOf(txtParking.getText());
                nbre = Float.valueOf(txtNbreJour.getText());
                manut = Float.valueOf(txtManutention.getText());
                fradmin = Float.valueOf(txtFraisAdmin.getText());

                //calcul
                float calc_surv1, calc_surv2, calc_tva, calc_fradmin, calc_totalht, calc_totalttc;
                calc_surv1 = (float) (poids * 0.005);
                txtSurv1.setText("" + calc_surv1);

                calc_surv2 = (float) (poids * 0.03 * (nbre - 2));
                txtSurv2.setText("" + calc_surv2);

                calc_totalht = (calc_surv1 + calc_surv2 + manut + park);
                calc_tva = (float) (calc_totalht * 0.16);
                txtTva.setText("" + calc_tva);

                //calcul total
                calc_totalttc = (calc_totalht + calc_tva);
                txtTotal.setText("" + calc_totalttc);
            }
        }
    }//GEN-LAST:event_lbCalculMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if (jXDatePicker1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Entrez la Date SVP", "Entry_Vehicule Error", JOptionPane.WARNING_MESSAGE);
        } else {
            if (cmbType.getSelectedItem().toString().equals("IT")) {
                try {
                    // code ici
                    fact.setId(txtId.getText());
                    ev.setId(cmbIdVehicule.getSelectedItem().toString());
                    fact.setEntry_Vehicule(ev);
                    fact.setDate_sortie(new Date(jXDatePicker1.getDate().getYear(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getDate()));
                    fact.setType_Facturation(cmbType.getSelectedItem().toString());
                    fact.setNom_client_fidele(txtClient_Fidele.getText());
                    fact.setDescription(txtDescription.getText());
                    fact.setPoids_facture(txtPoids.getText());
                    fact.setNbre_jour(txtNbreJour.getText());
                    fact.setTotal(Float.valueOf(txtTotal.getText()));
                    mois.setMois(cmbMois.getSelectedItem().toString());
                    an.setAnnee(cmbAnnee.getSelectedItem().toString());
                    fact.setMois(mois);
                    fact.setAnnee(an);
                    if (fact.Enregsitrer()) {
                        JOptionPane.showMessageDialog(null, "Facture etablie avec succes", "Facturation Message", JOptionPane.INFORMATION_MESSAGE);
                        ClsHelper.Load_TblData(jTable1, "SELECT * FROM tFacturation");
                        txtId.setText("FACT0" + ClsHelper.Increment_IDStr("tFacturation"));
                        changeStateEntry(cmbIdVehicule.getSelectedItem().toString());

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
                }
            } else if (cmbType.getSelectedItem().toString().equals("CLIENT FIDELE")) {
                try {
                    // code ici
                    fact.setId(txtId.getText());
                    ev.setId(cmbIdVehicule.getSelectedItem().toString());
                    fact.setEntry_Vehicule(ev);
                    fact.setDate_sortie(new Date(jXDatePicker1.getDate().getYear(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getDate()));
                    fact.setType_Facturation(cmbType.getSelectedItem().toString());
                    fact.setNom_client_fidele(txtClient_Fidele.getText());
                    fact.setDescription(txtDescription.getText());
                    fact.setTotal(Float.valueOf(txtTotal.getText()));
                    mois.setMois(cmbMois.getSelectedItem().toString());
                    an.setAnnee(cmbAnnee.getSelectedItem().toString());
                    fact.setMois(mois);
                    fact.setAnnee(an);
                    if (fact.Enregsitrer()) {
                        JOptionPane.showMessageDialog(null, "Facture etablie avec succes", "Facturation Message", JOptionPane.INFORMATION_MESSAGE);
                        ClsHelper.Load_TblData(jTable1, "SELECT * FROM tFacturation");
                        txtId.setText("FACT0" + ClsHelper.Increment_IDStr("tFacturation"));
                        changeStateEntry(cmbIdVehicule.getSelectedItem().toString());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
                }
            } else if (cmbType.getSelectedItem().toString().equals("AUTRE FACTURATION")) {
                try {
                    // code ici
                    fact.setId(txtId.getText());
                    ev.setId(cmbIdVehicule.getSelectedItem().toString());
                    fact.setEntry_Vehicule(ev);
                    fact.setDate_sortie(new Date(jXDatePicker1.getDate().getYear(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getDate()));
                    fact.setType_Facturation(cmbType.getSelectedItem().toString());
                    fact.setNom_client_fidele(txtClient_Fidele.getText());
                    fact.setDescription(txtDescription.getText());
                    fact.setTotal(Float.valueOf(txtTotal.getText()));
                    mois.setMois(cmbMois.getSelectedItem().toString());
                    an.setAnnee(cmbAnnee.getSelectedItem().toString());
                    fact.setMois(mois);
                    fact.setAnnee(an);
                    if (fact.Enregsitrer()) {
                        JOptionPane.showMessageDialog(null, "Facture etablie avec succes", "Facturation Message", JOptionPane.INFORMATION_MESSAGE);
                        ClsHelper.Load_TblData(jTable1, "SELECT * FROM tFacturation");
                        txtId.setText("FACT0" + ClsHelper.Increment_IDStr("tFacturation"));
                        changeStateEntry(cmbIdVehicule.getSelectedItem().toString());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
                }
            } else if (cmbType.getSelectedItem().toString().equals("FACTURATION NORMALE")) {
                try {
                    // code ici
                    fact.setId(txtId.getText());
                    ev.setId(cmbIdVehicule.getSelectedItem().toString());
                    fact.setEntry_Vehicule(ev);
                    fact.setDate_sortie(new Date(jXDatePicker1.getDate().getYear(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getDate()));
                    fact.setType_Facturation(cmbType.getSelectedItem().toString());
                    fact.setNom_client_fidele(txtClient_Fidele.getText());
                    fact.setDescription(txtDescription.getText());
                    fact.setPoids_facture(txtPoids.getText());
                    fact.setNbre_jour(txtNbreJour.getText());
                    fact.setParking(txtParking.getText());
                    fact.setSureveillance_1(txtSurv1.getText());
                    fact.setSureveillance_2(txtSurv2.getText());
                    fact.setManutention(txtManutention.getText());
                    fact.setTva(txtTva.getText());
                    fact.setFrais_admin(txtFraisAdmin.getText());
                    fact.setTotal(Float.valueOf(txtTotal.getText()));
                    mois.setMois(cmbMois.getSelectedItem().toString());
                    an.setAnnee(cmbAnnee.getSelectedItem().toString());
                    fact.setMois(mois);
                    fact.setAnnee(an);
                    if (fact.Enregsitrer()) {
                        JOptionPane.showMessageDialog(null, "Facture établie avec succès", "Facturation Message", JOptionPane.INFORMATION_MESSAGE);
                        ClsHelper.Load_TblData(jTable1, "SELECT * FROM tFacturation");
                        txtId.setText("FACT0" + ClsHelper.Increment_IDStr("tFacturation"));
                        changeStateEntry(cmbIdVehicule.getSelectedItem().toString());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Entry Loading Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void cmbIdVehiculePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbIdVehiculePopupMenuWillBecomeInvisible
        getEntry_Element(cmbIdVehicule.getSelectedItem().toString());
    }//GEN-LAST:event_cmbIdVehiculePopupMenuWillBecomeInvisible

    private void cmbMoisPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbMoisPopupMenuWillBecomeInvisible
        try {
            ClsHelper.Load_TblData(jTable1, "SELECT f.id ID, CONCAT(e.id,' - ',e.date_entree,' - ', e.plaque, ' - ', e.numero) VEHICULE, "
                    + "f.date_sortie DATE_SORTIE, f.nom_client_fidele CLIENT, f.[description] [DESCRIPTION], f.poids_facture POIDS_FACTURE, "
                    + "f.nbre_jour NOMBRE_JOURS, f.parking PARKING, f.sureveillance_1 [SURV 1], f.sureveillance_2 [SURV 2], f.manutention MANUTENTION, "
                    + "f.tva TVA, f.frais_admin FRAIS_ADMIN, f.total MONTANT_TOTAL FROM tFacturation f "
                    + "INNER JOIN tEntry_Vehicule e ON f.idEntree_vehicule = e.id "
                    + "INNER JOIN tMois m ON f.idMois = m.id "
                    + "INNER JOIN tAnnee a ON f.idAnnee = a.id "
                    + "WHERE m.mois = '" + cmbMois.getSelectedItem().toString() + "' "
                    + "AND a.annee = '" + cmbAnnee.getSelectedItem().toString() + "'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Facturation Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbMoisPopupMenuWillBecomeInvisible

    private void cmbAnneePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbAnneePopupMenuWillBecomeInvisible
        try {
            ClsHelper.Load_TblData(jTable1, "SELECT f.id ID, CONCAT(e.id,' - ',e.date_entree,' - ', e.plaque, ' - ', e.numero) VEHICULE, "
                    + "f.date_sortie DATE_SORTIE, f.nom_client_fidele CLIENT, f.[description] [DESCRIPTION], f.poids_facture POIDS_FACTURE, "
                    + "f.nbre_jour NOMBRE_JOURS, f.parking PARKING, f.sureveillance_1 [SURV 1], f.sureveillance_2 [SURV 2], f.manutention MANUTENTION, "
                    + "f.tva TVA, f.frais_admin FRAIS_ADMIN, f.total MONTANT_TOTAL FROM tFacturation f "
                    + "INNER JOIN tEntry_Vehicule e ON f.idEntree_vehicule = e.id "
                    + "INNER JOIN tMois m ON f.idMois = m.id "
                    + "INNER JOIN tAnnee a ON f.idAnnee = a.id "
                    + "WHERE m.mois = '" + cmbMois.getSelectedItem().toString() + "' "
                    + "AND a.annee = '" + cmbAnnee.getSelectedItem().toString() + "'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :\n" + e.getMessage(), "Facturation Loading Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbAnneePopupMenuWillBecomeInvisible

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAnnee;
    private javax.swing.JComboBox<String> cmbIdVehicule;
    private javax.swing.JComboBox<String> cmbMois;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbCalcul;
    private javax.swing.JLabel lbIdEntry;
    private javax.swing.JLabel lb_Num;
    private javax.swing.JLabel lb_Plaque;
    private javax.swing.JLabel lb_dateEntree;
    private javax.swing.JLabel lb_declarant;
    private javax.swing.JLabel lb_nature;
    private javax.swing.JLabel lb_poid;
    private javax.swing.JTextField txtClient_Fidele;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFraisAdmin;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtManutention;
    private javax.swing.JTextField txtNbreJour;
    private javax.swing.JTextField txtParking;
    private javax.swing.JTextField txtPoids;
    private javax.swing.JTextField txtSurv1;
    private javax.swing.JTextField txtSurv2;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTva;
    // End of variables declaration//GEN-END:variables
}
